In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
from tqdm import tqdm
%matplotlib inline
import xarray

In [10]:
batch_path = '/mnt/c/Users/nozom/Desktop/mass-suite/example_data/batch/'

In [229]:
reference = pd.read_csv(batch_path + os.listdir(batch_path)[0], sep="\\t", engine='python')

In [230]:
sample_df = pd.DataFrame()
# create empty dataframe
num_files = len([f for f in os.listdir(batch_path)if os.path.isfile(os.path.join(batch_path, f))])
for f in range(num_files-1):
    standard = pd.read_csv(batch_path + os.listdir(batch_path)[f+1], sep="\\t", engine='python')
    sample_df = sample_df.append(standard)
sorted_df = sample_df.sort_values(by=['RT (min)'])

In [231]:
sorted_df

,PeakID,Title,Scans,RT left(min),RT (min),RT right (min),Precursor m/z,Height,Area,Model masses,...,m/z matched,MS/MS matched,RT similarity,Dot product,Reverse dot product,Fragment presence %,Total score,S/N,MS1 isotopes,MSMS spectrum
1,1,Unknown,99,0.526550,0.581883,0.648283,217.0493,4816.349121,20366.517578,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,16.083630,216.94693:217 217.04927:5055 217.10075:1797 21...,NaN
0,0,Unknown,99,0.521017,0.581883,0.626150,201.0756,2129.107910,7226.377441,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,11.585760,201.01169:866 201.07327:2772 201.99001:303 202...,NaN
0,0,Unknown,98,0.521300,0.582167,0.637500,201.0696,2381.034180,8615.794922,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,13.050340,201.01112:1075 201.07257:2884 202.06036:936 20...,NaN
1,1,Unknown,98,0.543417,0.582167,0.643033,215.0042,4384.651367,16394.250000,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,27.317790,215.0042:5049 215.11922:253 216.00801:697 216....,NaN
2,2,Unknown,98,0.526833,0.582167,0.643033,217.0498,5029.392090,19556.232422,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,16.679890,216.94263:211 217.04976:5919 217.10106:1602 21...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,1180,Unknown,3817,21.039900,21.156100,21.211450,204.9958,1785.752441,13022.894531,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,15.779640,204.94688:544 204.9958:2098 205.07268:252 205....,NaN
1173,1173,Unknown,3817,20.979350,21.161970,21.300320,181.9808,2664.195801,29220.789062,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,28.520490,181.98076:2929 182.99393:707 183.06293:622 183...,NaN
1181,1181,Unknown,3823,21.167170,21.189300,21.360850,157.9763,10666.778320,82636.648438,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,21.389860,157.97629:10742 158.01251:43164 158.99947:1282...,NaN
1182,1182,Unknown,3831,21.172700,21.233580,21.283380,155.9746,32584.373047,211047.531250,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,9.405543,155.97357:33080 156.119:453 156.97598:2727 157...,NaN
1174,1174,Unknown,3830,20.968280,21.233900,21.311380,155.9739,29372.591797,377665.875000,NaN,...,False,False,NaN,NaN,NaN,NaN,NaN,143.477400,155.97388:29077 156.12317:417 156.97522:2417 1...,NaN

In [228]:
peak_num = 0
listing = []
for x in range(len(sorted_df)):
    if (abs(sorted_df.iat[x,4]-sorted_df.iat[(x-1),4]) >= 0.005) & (abs(sorted_df.iat[x,6]-sorted_df.iat[(x-1),6]) >= 0.0002):
        peak_num = peak_num + 1
        listing.append(peak_num)
    else:
        listing.append(peak_num)
sorted_df['unique peak'] = listing
sorted_df

,PeakID,Title,Scans,RT left(min),RT (min),RT right (min),Precursor m/z,Height,Area,Model masses,...,MS/MS matched,RT similarity,Dot product,Reverse dot product,Fragment presence %,Total score,S/N,MS1 isotopes,MSMS spectrum,unique peak
1,1,Unknown,99,0.526550,0.581883,0.648283,217.0493,4816.349121,20366.517578,NaN,...,False,NaN,NaN,NaN,NaN,NaN,16.083630,216.94693:217 217.04927:5055 217.10075:1797 21...,NaN,1
0,0,Unknown,99,0.521017,0.581883,0.626150,201.0756,2129.107910,7226.377441,NaN,...,False,NaN,NaN,NaN,NaN,NaN,11.585760,201.01169:866 201.07327:2772 201.99001:303 202...,NaN,1
0,0,Unknown,98,0.521300,0.582167,0.637500,201.0696,2381.034180,8615.794922,NaN,...,False,NaN,NaN,NaN,NaN,NaN,13.050340,201.01112:1075 201.07257:2884 202.06036:936 20...,NaN,1
1,1,Unknown,98,0.543417,0.582167,0.643033,215.0042,4384.651367,16394.250000,NaN,...,False,NaN,NaN,NaN,NaN,NaN,27.317790,215.0042:5049 215.11922:253 216.00801:697 216....,NaN,1
2,2,Unknown,98,0.526833,0.582167,0.643033,217.0498,5029.392090,19556.232422,NaN,...,False,NaN,NaN,NaN,NaN,NaN,16.679890,216.94263:211 217.04976:5919 217.10106:1602 21...,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,1180,Unknown,3817,21.039900,21.156100,21.211450,204.9958,1785.752441,13022.894531,NaN,...,False,NaN,NaN,NaN,NaN,NaN,15.779640,204.94688:544 204.9958:2098 205.07268:252 205....,NaN,766
1173,1173,Unknown,3817,20.979350,21.161970,21.300320,181.9808,2664.195801,29220.789062,NaN,...,False,NaN,NaN,NaN,NaN,NaN,28.520490,181.98076:2929 182.99393:707 183.06293:622 183...,NaN,767
1181,1181,Unknown,3823,21.167170,21.189300,21.360850,157.9763,10666.778320,82636.648438,NaN,...,False,NaN,NaN,NaN,NaN,NaN,21.389860,157.97629:10742 158.01251:43164 158.99947:1282...,NaN,768
1182,1182,Unknown,3831,21.172700,21.233580,21.283380,155.9746,32584.373047,211047.531250,NaN,...,False,NaN,NaN,NaN,NaN,NaN,9.405543,155.97357:33080 156.119:453 156.97598:2727 157...,NaN,769
1174,1174,Unknown,3830,20.968280,21.233900,21.311380,155.9739,29372.591797,377665.875000,NaN,...,False,NaN,NaN,NaN,NaN,NaN,143.477400,155.97388:29077 156.12317:417 156.97522:2417 1...,NaN,769

In [99]:
# thresholds
peak_area = 50000
rt_window = 1.5
s_n = 5

sample_df = pd.DataFrame()
# create empty dataframe
num_files = len([f for f in os.listdir(batch_path)if os.path.isfile(os.path.join(batch_path, f))])
for f in range(num_files-1):
    standard = pd.read_csv(batch_path + os.listdir(batch_path)[f+1], sep="\\t", engine='python')
    # was gonna append each row from the standard only if they passed the filter thresholds
    for i in range(len(standard)):
        if ((standard.at[i,'Area']) > (peak_area and standard.iat[i,4] < rt_window) & (standard.at[i,'S/N'] > s_n)):
            sample_df = sample_df.append(standard.iloc[i])

In [94]:
# thresholds
peak_area = 50000
rt_window = 1.5
s_n = 5

sample_df = pd.DataFrame()
# create empty dataframe
num_files = len([f for f in os.listdir(batch_path)if os.path.isfile(os.path.join(batch_path, f))])
for f in range(num_files-1):
    standard = pd.read_csv(batch_path + os.listdir(batch_path)[f+1], sep="\\t", engine='python')
    # was gonna append each row from the standard only if they passed the filter thresholds
    good = np.where((standard.at[i,'Area']) > (peak_area and standard.iat[i,4] < rt_window) & (standard.at[i,'S/N'] > s_n)):
            sample_df = df.append(standard.iloc[good])

SyntaxError: invalid syntax (<ipython-input-94-bb8ce40ce24d>, line 12)

In [100]:
sample_df
# This got messed up for some reason lol, was envisioning itll look similar to the reference but with more rows

,Adduct,Annotation tag (VS1.0),Area,Comment,Dot product,Formula,Fragment presence %,Height,InChIKey,Isotope,...,RT similarity,Reference RT,Reference m/z,Reverse dot product,S/N,SMILES,Scans,Title,Total score,m/z matched
0,[M+H]+,999.0,8615.794922,NaN,NaN,NaN,NaN,2381.034180,NaN,M + 0,...,NaN,NaN,NaN,NaN,13.050340,NaN,98.0,Unknown,NaN,0.0
1,[M+H]+,999.0,16394.250000,NaN,NaN,NaN,NaN,4384.651367,NaN,M + 0,...,NaN,NaN,NaN,NaN,27.317790,NaN,98.0,Unknown,NaN,0.0
2,[M+H]+,999.0,19556.232422,NaN,NaN,NaN,NaN,5029.392090,NaN,M + 0,...,NaN,NaN,NaN,NaN,16.679890,NaN,98.0,Unknown,NaN,0.0
3,[M+H]+,999.0,17208.224609,similar chromatogram in higher mz_0,NaN,NaN,NaN,4574.145508,NaN,M + 0,...,NaN,NaN,NaN,NaN,19.419960,NaN,99.0,Unknown,NaN,0.0
4,[M+H]+,999.0,82808.906250,NaN,NaN,NaN,NaN,18665.806641,NaN,M + 0,...,NaN,NaN,NaN,NaN,27.890480,NaN,99.0,Unknown,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,[M+H]+,999.0,18278.093750,NaN,NaN,NaN,NaN,2275.715332,NaN,M + 0,...,NaN,NaN,NaN,NaN,52.373000,NaN,3812.0,Unknown,NaN,0.0
1179,[M+H]+,999.0,29594.367188,NaN,NaN,NaN,NaN,2810.108887,NaN,M + 0,...,NaN,NaN,NaN,NaN,25.339680,NaN,3813.0,Unknown,NaN,0.0
1180,[M+H]+,999.0,13022.894531,NaN,NaN,NaN,NaN,1785.752441,NaN,M + 0,...,NaN,NaN,NaN,NaN,15.779640,NaN,3817.0,Unknown,NaN,0.0
1181,[M+H]+,999.0,82636.648438,NaN,NaN,NaN,NaN,10666.778320,NaN,M + 0,...,NaN,NaN,NaN,NaN,21.389860,NaN,3823.0,Unknown,NaN,0.0
1182,[M+H]+,999.0,211047.531250,NaN,NaN,NaN,NaN,32584.373047,NaN,M + 0,...,NaN,NaN,NaN,NaN,9.405543,NaN,3831.0,Unknown,NaN,0.0

In [88]:
# error
rt_error = 0.1
mz_error =0.00002

for i in range(len(sample_df)):
    for j in range(len(reference)):
        if((abs(sample_df[i,4]-reference[j,4]) < rt_error) and (abs(sample_df[i,6]-reference[j,6]) < mz_error)):
            reference = reference.append(sample_df.iloc[i])

KeyError: (0, 4)